[workspace]
resolver = "2"
members = ["shared", "poloniex", "scraper"]

[workspace.dependencies]
anyhow = "1"
reqwest = "0.12"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = "1"
