[workspace]
resolver = "2"
members = ["shared", "poloniex", "scraper"]

[workspace.dependencies]
anyhow = "1"
base64 = "0.22"
form_urlencoded = "1"
hmac = "0.12"
reqwest = "0.12"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
tokio = "1"
